# Generated migration - initial schema for Visitor Hostel Management System
from django.db import migrations, models
import django.db.models.deletion
import django.core.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('globals', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('total_rooms', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('contact_number', models.CharField(blank=True, max_length=15)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='RoomDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20)),
                ('room_type', models.CharField(choices=[('Single', 'Single'), ('Double', 'Double'), ('Suite', 'Suite'), ('Dormitory', 'Dormitory')], max_length=20)),
                ('floor', models.IntegerField(choices=[(0, 'Ground Floor'), (1, 'First Floor'), (2, 'Second Floor'), (3, 'Third Floor'), (4, 'Fourth Floor')], default=0)),
                ('bed_count', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('max_occupancy', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('has_ac', models.BooleanField(default=False)),
                ('has_attached_bathroom', models.BooleanField(default=True)),
                ('amenities', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Occupied', 'Occupied'), ('Maintenance', 'Under Maintenance'), ('Blocked', 'Blocked')], default='Available', max_length=20)),
                ('tariff_per_day', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tariff_faculty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tariff_staff', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tariff_student', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tariff_external', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='visitor_hostel.Building')),
            ],
            options={'ordering': ['building', 'room_number'], 'unique_together': {('building', 'room_number')}},
        ),
        migrations.CreateModel(
            name='BookingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(max_length=50, unique=True)),
                ('visitor_name', models.CharField(max_length=200)),
                ('visitor_category', models.CharField(choices=[('IIIT_Faculty', 'IIIT Faculty'), ('IIIT_Staff', 'IIIT Staff'), ('IIIT_Student', 'IIIT Student'), ('Guest_Speaker', 'Guest Speaker'), ('Examiner', 'External Examiner'), ('Official', 'Official Visitor'), ('Personal', 'Personal Guest'), ('Other', 'Other')], max_length=30)),
                ('visitor_organization', models.CharField(blank=True, max_length=200)),
                ('visitor_designation', models.CharField(blank=True, max_length=100)),
                ('visitor_phone', models.CharField(max_length=15)),
                ('visitor_email', models.EmailField(blank=True)),
                ('visitor_address', models.TextField(blank=True)),
                ('id_proof_type', models.CharField(blank=True, max_length=50)),
                ('id_proof_number', models.CharField(blank=True, max_length=50)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('number_of_guests', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('number_of_rooms', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('preferred_room_type', models.CharField(blank=True, choices=[('Single', 'Single'), ('Double', 'Double'), ('Suite', 'Suite'), ('Dormitory', 'Dormitory')], max_length=20)),
                ('purpose', models.CharField(choices=[('Academic', 'Academic'), ('Conference', 'Conference / Seminar'), ('Official', 'Official Work'), ('Recruitment', 'Recruitment'), ('Personal', 'Personal'), ('Other', 'Other')], max_length=20)),
                ('purpose_details', models.TextField(blank=True)),
                ('bill_to_be_settled_by', models.CharField(choices=[('Intender', 'Intender'), ('Department', 'Department'), ('Project', 'Project Account'), ('Guest', 'Guest (Self)'), ('Institute', 'Institute')], default='Intender', max_length=20)),
                ('project_number', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Forwarded', 'Forwarded'), ('Confirmed', 'Confirmed'), ('CheckedIn', 'Checked In'), ('CheckedOut', 'Checked Out'), ('Cancelled', 'Cancelled'), ('Rejected', 'Rejected'), ('Expired', 'Expired')], default='Pending', max_length=20)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('remark', models.CharField(blank=True, max_length=500)),
                ('forwarded_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('actual_check_in', models.DateTimeField(blank=True, null=True)),
                ('actual_check_out', models.DateTimeField(blank=True, null=True)),
                ('is_offline', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vh_bookings', to='globals.extrainfo')),
                ('intender_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='globals.departmentinfo')),
                ('caretaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caretaker_bookings', to='globals.extrainfo')),
                ('forwarded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwarded_bookings', to='globals.extrainfo')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_bookings', to='globals.extrainfo')),
            ],
            options={'ordering': ['-booking_date']},
        ),
        migrations.CreateModel(
            name='RoomAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_allocations', to='visitor_hostel.BookingDetail')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='visitor_hostel.RoomDetail')),
                ('allocated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_allocations_done', to='globals.extrainfo')),
            ],
            options={'ordering': ['-allocated_at']},
        ),
        migrations.CreateModel(
            name='VisitorDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True)),
                ('id_proof_type', models.CharField(blank=True, max_length=50)),
                ('id_proof_number', models.CharField(blank=True, max_length=50)),
                ('relationship_to_intender', models.CharField(blank=True, max_length=100)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_details', to='visitor_hostel.BookingDetail')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('invoice_date', models.DateField()),
                ('room_charges', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('meal_charges', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('extra_charges', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('balance_due', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_mode', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Online', 'Online Transfer'), ('DD', 'Demand Draft')], max_length=20)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Generated', 'Generated'), ('Pending', 'Payment Pending'), ('Paid', 'Paid'), ('Cancelled', 'Cancelled'), ('Locked', 'Locked')], default='Generated', max_length=20)),
                ('billed_to_name', models.CharField(blank=True, max_length=200)),
                ('billed_to_address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='visitor_hostel.BookingDetail')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_bills', to='globals.extrainfo')),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('payment_date', models.DateTimeField()),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Online', 'Online Transfer'), ('DD', 'Demand Draft')], max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='visitor_hostel.Bill')),
                ('received_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_payments', to='globals.extrainfo')),
            ],
        ),
        migrations.CreateModel(
            name='MealBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_date', models.DateField()),
                ('meal_type', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('High_Tea', 'High Tea')], max_length=20)),
                ('number_of_persons', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('vegetarian', models.BooleanField(default=True)),
                ('special_requirements', models.TextField(blank=True)),
                ('rate_per_person', models.DecimalField(decimal_places=2, default=0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_bookings', to='visitor_hostel.BookingDetail')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_meals', to='globals.extrainfo')),
            ],
            options={'ordering': ['meal_date', 'meal_type'], 'unique_together': {('booking', 'meal_date', 'meal_type')}},
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Consumable', 'Consumable'), ('Asset', 'Asset / Reusable')], default='Consumable', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('usable_quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(default='piece', max_length=30)),
                ('purchase_bill_number', models.CharField(blank=True, max_length=100)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('threshold_quantity', models.IntegerField(default=5)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_added', to='globals.extrainfo')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_updated', to='globals.extrainfo')),
            ],
            options={'ordering': ['name'], 'verbose_name_plural': 'Inventory Items'},
        ),
        migrations.CreateModel(
            name='InventoryUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_usages', to='visitor_hostel.BookingDetail')),
                ('inventory_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='visitor_hostel.Inventory')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_usages_recorded', to='globals.extrainfo')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='visitor_hostel.BookingDetail')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vh_notifications', to='auth.user')),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='GuestFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_cleanliness', models.IntegerField(blank=True, null=True)),
                ('room_amenities', models.IntegerField(blank=True, null=True)),
                ('staff_behavior', models.IntegerField(blank=True, null=True)),
                ('food_quality', models.IntegerField(blank=True, null=True)),
                ('overall_experience', models.IntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('suggestions', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='visitor_hostel.BookingDetail')),
            ],
        ),
    ]
